// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_main.h"
#include "ui_wifiscreen.h"
#include "ui_location.h"
#include "ui_unitsscreen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * lkeebpopup_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * lkeepgoodbye_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wifikeebpopup_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wifikeebgoodbye_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_clockface286oPTimized);
LV_FONT_DECLARE(ui_font_quote30oPTimized);
LV_FONT_DECLARE(ui_font_settings32);
LV_FONT_DECLARE(ui_font_status26oPTimized);
LV_FONT_DECLARE(ui_font_weather96);
LV_FONT_DECLARE(ui_font_weatherdegrees32oPTimized);
LV_FONT_DECLARE(ui_font_weatherdegrees96oPTimized);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
