// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void connect2wifi(lv_event_t * e)
{
	// Your code here
}

void savecityandoffset(lv_event_t * e)
{
	// Your code here
}

void saveunits(lv_event_t * e)
{
	// Your code here
}
