// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_LOCATION_H
#define UI_LOCATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_location
extern void ui_location_screen_init(void);
extern void ui_location_screen_destroy(void);
extern lv_obj_t * ui_location;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern void ui_event_cityta(lv_event_t * e);
extern lv_obj_t * ui_cityta;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Label4;
extern void ui_event_cancelbutton67(lv_event_t * e);
extern lv_obj_t * ui_cancelbutton67;
extern lv_obj_t * ui_coonect2;
extern void ui_event_cancelbutton1(lv_event_t * e);
extern lv_obj_t * ui_cancelbutton1;
extern lv_obj_t * ui_coonect1;
extern lv_obj_t * ui_lkeeb;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

