// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_location = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_cityta = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_cancelbutton67 = NULL;
lv_obj_t * ui_coonect2 = NULL;
lv_obj_t * ui_cancelbutton1 = NULL;
lv_obj_t * ui_coonect1 = NULL;
lv_obj_t * ui_lkeeb = NULL;
// event funtions
void ui_event_cityta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        lkeebpopup_Animation(ui_lkeeb, 200);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        lkeepgoodbye_Animation(ui_lkeeb, 200);
    }
}

void ui_event_cancelbutton67(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_main_screen_init);
    }
}

void ui_event_cancelbutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_main_screen_init);
        savecityandoffset(e);
    }
}

// build funtions

void ui_location_screen_init(void)
{
    ui_location = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_location, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_location, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_location);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -207);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SET LOCATION");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_location);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -320);
    lv_obj_set_y(ui_Label2, -137);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "CITY:");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cityta = lv_textarea_create(ui_location);
    lv_obj_set_width(ui_cityta, 450);
    lv_obj_set_height(ui_cityta, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_cityta, -35);
    lv_obj_set_y(ui_cityta, -137);
    lv_obj_set_align(ui_cityta, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_cityta, true);
    lv_obj_set_style_text_color(ui_cityta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cityta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cityta, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cityta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cityta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cityta, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cityta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cityta, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cityta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cityta, 2, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_location);
    lv_dropdown_set_options(ui_Dropdown1,
                            "UTC-12\nUTC-11\nUTC-10\nUTC-9\nUTC-8\nUTC-7\nUTC-6\nUTC-5\nUTC-4\nUTC-3\nUTC-2\nUTC-1\nUTC=0\nUTC+1\nUTC+2\nUTC+3\nUTC+3:30\nUTC+4\nUTC+5\nUTC+5:30\nUTC+6\nUTC+7\nUTC+8\nUTC+9\nUTC+9:30\nUTC+10\nUTC+11\nUTC+12\nUTC+13\nUTC+14");
    lv_obj_set_width(ui_Dropdown1, 169);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -168);
    lv_obj_set_y(ui_Dropdown1, -56);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Dropdown1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x131313),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_location);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -320);
    lv_obj_set_y(ui_Label4, -56);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "OFFSET:");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbutton67 = lv_button_create(ui_location);
    lv_obj_set_width(ui_cancelbutton67, 248);
    lv_obj_set_height(ui_cancelbutton67, 41);
    lv_obj_set_x(ui_cancelbutton67, -254);
    lv_obj_set_y(ui_cancelbutton67, 25);
    lv_obj_set_align(ui_cancelbutton67, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelbutton67, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancelbutton67, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cancelbutton67, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cancelbutton67, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelbutton67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cancelbutton67, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cancelbutton67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancelbutton67, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cancelbutton67, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cancelbutton67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cancelbutton67, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_cancelbutton67, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coonect2 = lv_label_create(ui_cancelbutton67);
    lv_obj_set_width(ui_coonect2, 233);
    lv_obj_set_height(ui_coonect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coonect2, 0);
    lv_obj_set_y(ui_coonect2, 1);
    lv_obj_set_align(ui_coonect2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coonect2, "CANCEL");
    lv_obj_set_style_text_color(ui_coonect2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coonect2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coonect2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coonect2, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbutton1 = lv_button_create(ui_location);
    lv_obj_set_width(ui_cancelbutton1, 248);
    lv_obj_set_height(ui_cancelbutton1, 41);
    lv_obj_set_x(ui_cancelbutton1, 254);
    lv_obj_set_y(ui_cancelbutton1, 25);
    lv_obj_set_align(ui_cancelbutton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelbutton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancelbutton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cancelbutton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cancelbutton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelbutton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cancelbutton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cancelbutton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancelbutton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cancelbutton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cancelbutton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cancelbutton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_cancelbutton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coonect1 = lv_label_create(ui_cancelbutton1);
    lv_obj_set_width(ui_coonect1, 233);
    lv_obj_set_height(ui_coonect1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coonect1, 0);
    lv_obj_set_y(ui_coonect1, 1);
    lv_obj_set_align(ui_coonect1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coonect1, "SAVE");
    lv_obj_set_style_text_color(ui_coonect1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coonect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coonect1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coonect1, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lkeeb = lv_keyboard_create(ui_location);
    lv_obj_set_width(ui_lkeeb, 800);
    lv_obj_set_height(ui_lkeeb, 245);
    lv_obj_set_x(ui_lkeeb, 0);
    lv_obj_set_y(ui_lkeeb, 367);
    lv_obj_set_align(ui_lkeeb, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_lkeeb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lkeeb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_lkeeb, lv_color_hex(0xB7B7B7), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lkeeb, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_lkeeb, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lkeeb, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lkeeb, lv_color_hex(0x848484), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lkeeb, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_lkeeb, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lkeeb, 255, LV_PART_ITEMS | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_cityta, ui_event_cityta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbutton67, ui_event_cancelbutton67, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbutton1, ui_event_cancelbutton1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_lkeeb, ui_cityta);

}

void ui_location_screen_destroy(void)
{
    if(ui_location) lv_obj_del(ui_location);

    // NULL screen variables
    ui_location = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_cityta = NULL;
    ui_Dropdown1 = NULL;
    ui_Label4 = NULL;
    ui_cancelbutton67 = NULL;
    ui_coonect2 = NULL;
    ui_cancelbutton1 = NULL;
    ui_coonect1 = NULL;
    ui_lkeeb = NULL;

}
