// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_dateandwifi;
extern lv_obj_t * ui_wifiStrength;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_border;
extern lv_obj_t * ui_viewport;
extern lv_obj_t * ui_weatherporter;
extern lv_obj_t * ui_day2;
extern lv_obj_t * ui_humanday2;
extern lv_obj_t * ui_nextdaysep1;
extern lv_obj_t * ui_day2icon;
extern lv_obj_t * ui_day2deg;
extern lv_obj_t * ui_next4days;
extern lv_obj_t * ui_todayweather;
extern lv_obj_t * ui_day1;
extern lv_obj_t * ui_todayicon;
extern lv_obj_t * ui_todayweek;
extern lv_obj_t * ui_day3;
extern lv_obj_t * ui_humanday3;
extern lv_obj_t * ui_nextdaysep2;
extern lv_obj_t * ui_day3icon;
extern lv_obj_t * ui_day3deg;
extern lv_obj_t * ui_day4;
extern lv_obj_t * ui_humanday4;
extern lv_obj_t * ui_nextdaysep3;
extern lv_obj_t * ui_day4icon;
extern lv_obj_t * ui_day4deg;
extern lv_obj_t * ui_day5;
extern lv_obj_t * ui_humanday5;
extern lv_obj_t * ui_nextdaysep4;
extern lv_obj_t * ui_day5icon;
extern lv_obj_t * ui_day5deg;
extern lv_obj_t * ui_day6;
extern lv_obj_t * ui_humanday6;
extern lv_obj_t * ui_nextdaysep5;
extern lv_obj_t * ui_day6icon;
extern lv_obj_t * ui_day6deg;
extern lv_obj_t * ui_day7;
extern lv_obj_t * ui_humanday7;
extern lv_obj_t * ui_nextdaysep6;
extern lv_obj_t * ui_day7icon;
extern lv_obj_t * ui_day7deg;
extern lv_obj_t * ui_day8;
extern lv_obj_t * ui_humanday8;
extern lv_obj_t * ui_nextdaysep7;
extern lv_obj_t * ui_day8icon;
extern lv_obj_t * ui_day8deg;
extern lv_obj_t * ui_day9;
extern lv_obj_t * ui_humanday9;
extern lv_obj_t * ui_day9icon;
extern lv_obj_t * ui_day9deg;
extern lv_obj_t * ui_nextdaysep8;
extern lv_obj_t * ui_separator;
extern lv_obj_t * ui_timekeep;
extern lv_obj_t * ui_quote;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_config;
extern void ui_event_wifi(lv_event_t * e);
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_iconwifi;
extern lv_obj_t * ui_labelwifi;
extern void ui_event_timezone(lv_event_t * e);
extern lv_obj_t * ui_timezone;
extern lv_obj_t * ui_iconglobe;
extern lv_obj_t * ui_labeltimezone;
extern void ui_event_units(lv_event_t * e);
extern lv_obj_t * ui_units;
extern lv_obj_t * ui_iconunits;
extern lv_obj_t * ui_labelunits;
// CUSTOM VARIABLES
extern lv_obj_t * uic_todayweek;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

