// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_todayweek;
lv_obj_t * ui_main = NULL;
lv_obj_t * ui_dateandwifi = NULL;
lv_obj_t * ui_wifiStrength = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_border = NULL;
lv_obj_t * ui_viewport = NULL;
lv_obj_t * ui_weatherporter = NULL;
lv_obj_t * ui_day2 = NULL;
lv_obj_t * ui_humanday2 = NULL;
lv_obj_t * ui_nextdaysep1 = NULL;
lv_obj_t * ui_day2icon = NULL;
lv_obj_t * ui_day2deg = NULL;
lv_obj_t * ui_next4days = NULL;
lv_obj_t * ui_todayweather = NULL;
lv_obj_t * ui_day1 = NULL;
lv_obj_t * ui_todayicon = NULL;
lv_obj_t * ui_todayweek = NULL;
lv_obj_t * ui_day3 = NULL;
lv_obj_t * ui_humanday3 = NULL;
lv_obj_t * ui_nextdaysep2 = NULL;
lv_obj_t * ui_day3icon = NULL;
lv_obj_t * ui_day3deg = NULL;
lv_obj_t * ui_day4 = NULL;
lv_obj_t * ui_humanday4 = NULL;
lv_obj_t * ui_nextdaysep3 = NULL;
lv_obj_t * ui_day4icon = NULL;
lv_obj_t * ui_day4deg = NULL;
lv_obj_t * ui_day5 = NULL;
lv_obj_t * ui_humanday5 = NULL;
lv_obj_t * ui_nextdaysep4 = NULL;
lv_obj_t * ui_day5icon = NULL;
lv_obj_t * ui_day5deg = NULL;
lv_obj_t * ui_day6 = NULL;
lv_obj_t * ui_humanday6 = NULL;
lv_obj_t * ui_nextdaysep5 = NULL;
lv_obj_t * ui_day6icon = NULL;
lv_obj_t * ui_day6deg = NULL;
lv_obj_t * ui_day7 = NULL;
lv_obj_t * ui_humanday7 = NULL;
lv_obj_t * ui_nextdaysep6 = NULL;
lv_obj_t * ui_day7icon = NULL;
lv_obj_t * ui_day7deg = NULL;
lv_obj_t * ui_day8 = NULL;
lv_obj_t * ui_humanday8 = NULL;
lv_obj_t * ui_nextdaysep7 = NULL;
lv_obj_t * ui_day8icon = NULL;
lv_obj_t * ui_day8deg = NULL;
lv_obj_t * ui_day9 = NULL;
lv_obj_t * ui_humanday9 = NULL;
lv_obj_t * ui_day9icon = NULL;
lv_obj_t * ui_day9deg = NULL;
lv_obj_t * ui_nextdaysep8 = NULL;
lv_obj_t * ui_separator = NULL;
lv_obj_t * ui_timekeep = NULL;
lv_obj_t * ui_quote = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_config = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_iconwifi = NULL;
lv_obj_t * ui_labelwifi = NULL;
lv_obj_t * ui_timezone = NULL;
lv_obj_t * ui_iconglobe = NULL;
lv_obj_t * ui_labeltimezone = NULL;
lv_obj_t * ui_units = NULL;
lv_obj_t * ui_iconunits = NULL;
lv_obj_t * ui_labelunits = NULL;
// event funtions
void ui_event_wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiscreen, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_wifiscreen_screen_init);
    }
}

void ui_event_timezone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_location, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_location_screen_init);
    }
}

void ui_event_units(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_unitsscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_unitsscreen_screen_init);
    }
}

// build funtions

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_main, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_main, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateandwifi = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_dateandwifi);
    lv_obj_set_width(ui_dateandwifi, 742);
    lv_obj_set_height(ui_dateandwifi, 50);
    lv_obj_set_x(ui_dateandwifi, 0);
    lv_obj_set_y(ui_dateandwifi, -210);
    lv_obj_set_align(ui_dateandwifi, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dateandwifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_wifiStrength = lv_label_create(ui_dateandwifi);
    lv_obj_set_width(ui_wifiStrength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStrength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStrength, 310);
    lv_obj_set_y(ui_wifiStrength, 0);
    lv_obj_set_align(ui_wifiStrength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStrength, "-45dBm");
    lv_obj_remove_flag(ui_wifiStrength, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_wifiStrength, lv_color_hex(0x0CB311), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiStrength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiStrength, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_dateandwifi);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -320);
    lv_obj_set_y(ui_date, 0);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "06/07");
    lv_obj_remove_flag(ui_date, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_border = lv_obj_create(ui_dateandwifi);
    lv_obj_set_width(ui_border, 742);
    lv_obj_set_height(ui_border, 50);
    lv_obj_set_align(ui_border, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_border, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_border, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_border, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_border, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewport = lv_obj_create(ui_main);
    lv_obj_set_width(ui_viewport, 842);
    lv_obj_set_height(ui_viewport, 409);
    lv_obj_set_x(ui_viewport, 0);
    lv_obj_set_y(ui_viewport, 35);
    lv_obj_set_align(ui_viewport, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_viewport, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_viewport, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewport, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_viewport, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_viewport, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_viewport, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_radius(ui_viewport, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_viewport, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_viewport, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_viewport, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherporter = lv_obj_create(ui_viewport);
    lv_obj_remove_style_all(ui_weatherporter);
    lv_obj_set_width(ui_weatherporter, 800);
    lv_obj_set_height(ui_weatherporter, 426);
    lv_obj_set_x(ui_weatherporter, -800);
    lv_obj_set_y(ui_weatherporter, -5);
    lv_obj_set_align(ui_weatherporter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherporter, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_weatherporter,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_weatherporter, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_weatherporter, LV_SCROLL_SNAP_CENTER);

    ui_day2 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day2);
    lv_obj_set_width(ui_day2, 100);
    lv_obj_set_height(ui_day2, 161);
    lv_obj_set_x(ui_day2, -351);
    lv_obj_set_y(ui_day2, 135);
    lv_obj_set_align(ui_day2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday2 = lv_label_create(ui_day2);
    lv_obj_set_width(ui_humanday2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday2, -3);
    lv_obj_set_y(ui_humanday2, -50);
    lv_obj_set_align(ui_humanday2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday2, "Thu");
    lv_obj_remove_flag(ui_humanday2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday2, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep1 = lv_obj_create(ui_day2);
    lv_obj_set_width(ui_nextdaysep1, 2);
    lv_obj_set_height(ui_nextdaysep1, 170);
    lv_obj_set_x(ui_nextdaysep1, 49);
    lv_obj_set_y(ui_nextdaysep1, 0);
    lv_obj_set_align(ui_nextdaysep1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2icon = lv_label_create(ui_day2);
    lv_obj_set_width(ui_day2icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day2icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day2icon, "B");
    lv_obj_remove_flag(ui_day2icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day2icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day2icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day2icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2deg = lv_label_create(ui_day2);
    lv_obj_set_width(ui_day2deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2deg, 0);
    lv_obj_set_y(ui_day2deg, 50);
    lv_obj_set_align(ui_day2deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day2deg, "0°");
    lv_obj_remove_flag(ui_day2deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day2deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day2deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day2deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_next4days = lv_label_create(ui_weatherporter);
    lv_obj_set_width(ui_next4days, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_next4days, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_next4days, 0);
    lv_obj_set_y(ui_next4days, 15);
    lv_obj_set_align(ui_next4days, LV_ALIGN_CENTER);
    lv_label_set_text(ui_next4days, "Next 8 days");
    lv_obj_remove_flag(ui_next4days, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_next4days, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_next4days, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_next4days, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todayweather = lv_label_create(ui_weatherporter);
    lv_obj_set_width(ui_todayweather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todayweather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todayweather, -3);
    lv_obj_set_y(ui_todayweather, -36);
    lv_obj_set_align(ui_todayweather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todayweather, "Unknown");
    lv_obj_remove_flag(ui_todayweather, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_todayweather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todayweather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_todayweather, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day1);
    lv_obj_set_width(ui_day1, 178);
    lv_obj_set_height(ui_day1, 138);
    lv_obj_set_x(ui_day1, 0);
    lv_obj_set_y(ui_day1, -111);
    lv_obj_set_align(ui_day1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_outline_color(ui_day1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todayicon = lv_label_create(ui_day1);
    lv_obj_set_width(ui_todayicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todayicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todayicon, 0);
    lv_obj_set_y(ui_todayicon, 13);
    lv_obj_set_align(ui_todayicon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todayicon, "---");
    lv_obj_remove_flag(ui_todayicon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_todayicon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todayicon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_todayicon, &ui_font_weatherdegrees96oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todayweek = lv_label_create(ui_day1);
    lv_obj_set_width(ui_todayweek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todayweek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todayweek, -2);
    lv_obj_set_y(ui_todayweek, -50);
    lv_obj_set_align(ui_todayweek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todayweek, "Thu");
    lv_obj_remove_flag(ui_todayweek, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_todayweek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todayweek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_todayweek, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day3);
    lv_obj_set_width(ui_day3, 100);
    lv_obj_set_height(ui_day3, 161);
    lv_obj_set_x(ui_day3, -249);
    lv_obj_set_y(ui_day3, 134);
    lv_obj_set_align(ui_day3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday3 = lv_label_create(ui_day3);
    lv_obj_set_width(ui_humanday3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday3, -3);
    lv_obj_set_y(ui_humanday3, -50);
    lv_obj_set_align(ui_humanday3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday3, "Thu");
    lv_obj_remove_flag(ui_humanday3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday3, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep2 = lv_obj_create(ui_day3);
    lv_obj_set_width(ui_nextdaysep2, 2);
    lv_obj_set_height(ui_nextdaysep2, 170);
    lv_obj_set_x(ui_nextdaysep2, 49);
    lv_obj_set_y(ui_nextdaysep2, 0);
    lv_obj_set_align(ui_nextdaysep2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3icon = lv_label_create(ui_day3);
    lv_obj_set_width(ui_day3icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day3icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day3icon, "B");
    lv_obj_remove_flag(ui_day3icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day3icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day3icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day3icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3deg = lv_label_create(ui_day3);
    lv_obj_set_width(ui_day3deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3deg, 0);
    lv_obj_set_y(ui_day3deg, 50);
    lv_obj_set_align(ui_day3deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day3deg, "0°");
    lv_obj_remove_flag(ui_day3deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day3deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day3deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day3deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day4 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day4);
    lv_obj_set_width(ui_day4, 100);
    lv_obj_set_height(ui_day4, 161);
    lv_obj_set_x(ui_day4, -149);
    lv_obj_set_y(ui_day4, 134);
    lv_obj_set_align(ui_day4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday4 = lv_label_create(ui_day4);
    lv_obj_set_width(ui_humanday4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday4, -3);
    lv_obj_set_y(ui_humanday4, -50);
    lv_obj_set_align(ui_humanday4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday4, "Thu");
    lv_obj_remove_flag(ui_humanday4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday4, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep3 = lv_obj_create(ui_day4);
    lv_obj_set_width(ui_nextdaysep3, 2);
    lv_obj_set_height(ui_nextdaysep3, 170);
    lv_obj_set_x(ui_nextdaysep3, 49);
    lv_obj_set_y(ui_nextdaysep3, 0);
    lv_obj_set_align(ui_nextdaysep3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day4icon = lv_label_create(ui_day4);
    lv_obj_set_width(ui_day4icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day4icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day4icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day4icon, "B");
    lv_obj_remove_flag(ui_day4icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day4icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day4icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day4icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day4deg = lv_label_create(ui_day4);
    lv_obj_set_width(ui_day4deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day4deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day4deg, 0);
    lv_obj_set_y(ui_day4deg, 50);
    lv_obj_set_align(ui_day4deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day4deg, "0°");
    lv_obj_set_style_text_color(ui_day4deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day4deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day4deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day5 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day5);
    lv_obj_set_width(ui_day5, 100);
    lv_obj_set_height(ui_day5, 161);
    lv_obj_set_x(ui_day5, -49);
    lv_obj_set_y(ui_day5, 134);
    lv_obj_set_align(ui_day5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_humanday5 = lv_label_create(ui_day5);
    lv_obj_set_width(ui_humanday5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday5, -3);
    lv_obj_set_y(ui_humanday5, -50);
    lv_obj_set_align(ui_humanday5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday5, "Thu");
    lv_obj_remove_flag(ui_humanday5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday5, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep4 = lv_obj_create(ui_day5);
    lv_obj_set_width(ui_nextdaysep4, 2);
    lv_obj_set_height(ui_nextdaysep4, 170);
    lv_obj_set_x(ui_nextdaysep4, 49);
    lv_obj_set_y(ui_nextdaysep4, 0);
    lv_obj_set_align(ui_nextdaysep4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day5icon = lv_label_create(ui_day5);
    lv_obj_set_width(ui_day5icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day5icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day5icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day5icon, "B");
    lv_obj_remove_flag(ui_day5icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_day5icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day5icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day5icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day5deg = lv_label_create(ui_day5);
    lv_obj_set_width(ui_day5deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day5deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day5deg, 0);
    lv_obj_set_y(ui_day5deg, 50);
    lv_obj_set_align(ui_day5deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day5deg, "0°");
    lv_obj_remove_flag(ui_day5deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day5deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day5deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day5deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day6 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day6);
    lv_obj_set_width(ui_day6, 100);
    lv_obj_set_height(ui_day6, 161);
    lv_obj_set_x(ui_day6, 51);
    lv_obj_set_y(ui_day6, 136);
    lv_obj_set_align(ui_day6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday6 = lv_label_create(ui_day6);
    lv_obj_set_width(ui_humanday6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday6, -3);
    lv_obj_set_y(ui_humanday6, -50);
    lv_obj_set_align(ui_humanday6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday6, "Thu");
    lv_obj_remove_flag(ui_humanday6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday6, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep5 = lv_obj_create(ui_day6);
    lv_obj_set_width(ui_nextdaysep5, 2);
    lv_obj_set_height(ui_nextdaysep5, 170);
    lv_obj_set_x(ui_nextdaysep5, 49);
    lv_obj_set_y(ui_nextdaysep5, 0);
    lv_obj_set_align(ui_nextdaysep5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day6icon = lv_label_create(ui_day6);
    lv_obj_set_width(ui_day6icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day6icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day6icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day6icon, "B");
    lv_obj_remove_flag(ui_day6icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_day6icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day6icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day6icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day6deg = lv_label_create(ui_day6);
    lv_obj_set_width(ui_day6deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day6deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day6deg, 0);
    lv_obj_set_y(ui_day6deg, 50);
    lv_obj_set_align(ui_day6deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day6deg, "0°");
    lv_obj_remove_flag(ui_day6deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day6deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day6deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day6deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day7 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day7);
    lv_obj_set_width(ui_day7, 100);
    lv_obj_set_height(ui_day7, 161);
    lv_obj_set_x(ui_day7, 152);
    lv_obj_set_y(ui_day7, 136);
    lv_obj_set_align(ui_day7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday7 = lv_label_create(ui_day7);
    lv_obj_set_width(ui_humanday7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday7, -3);
    lv_obj_set_y(ui_humanday7, -50);
    lv_obj_set_align(ui_humanday7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday7, "Thu");
    lv_obj_remove_flag(ui_humanday7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday7, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep6 = lv_obj_create(ui_day7);
    lv_obj_set_width(ui_nextdaysep6, 2);
    lv_obj_set_height(ui_nextdaysep6, 170);
    lv_obj_set_x(ui_nextdaysep6, 49);
    lv_obj_set_y(ui_nextdaysep6, 0);
    lv_obj_set_align(ui_nextdaysep6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day7icon = lv_label_create(ui_day7);
    lv_obj_set_width(ui_day7icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day7icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day7icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day7icon, "B");
    lv_obj_remove_flag(ui_day7icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day7icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day7icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day7icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day7deg = lv_label_create(ui_day7);
    lv_obj_set_width(ui_day7deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day7deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day7deg, 0);
    lv_obj_set_y(ui_day7deg, 50);
    lv_obj_set_align(ui_day7deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day7deg, "0°");
    lv_obj_remove_flag(ui_day7deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day7deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day7deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day7deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day8 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day8);
    lv_obj_set_width(ui_day8, 100);
    lv_obj_set_height(ui_day8, 161);
    lv_obj_set_x(ui_day8, 252);
    lv_obj_set_y(ui_day8, 136);
    lv_obj_set_align(ui_day8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday8 = lv_label_create(ui_day8);
    lv_obj_set_width(ui_humanday8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday8, -3);
    lv_obj_set_y(ui_humanday8, -50);
    lv_obj_set_align(ui_humanday8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday8, "Thu");
    lv_obj_remove_flag(ui_humanday8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday8, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep7 = lv_obj_create(ui_day8);
    lv_obj_set_width(ui_nextdaysep7, 2);
    lv_obj_set_height(ui_nextdaysep7, 170);
    lv_obj_set_x(ui_nextdaysep7, 49);
    lv_obj_set_y(ui_nextdaysep7, 0);
    lv_obj_set_align(ui_nextdaysep7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day8icon = lv_label_create(ui_day8);
    lv_obj_set_width(ui_day8icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day8icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day8icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day8icon, "B");
    lv_obj_remove_flag(ui_day8icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day8icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day8icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day8icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day8deg = lv_label_create(ui_day8);
    lv_obj_set_width(ui_day8deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day8deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day8deg, 0);
    lv_obj_set_y(ui_day8deg, 50);
    lv_obj_set_align(ui_day8deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day8deg, "0°");
    lv_obj_remove_flag(ui_day8deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day8deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day8deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day8deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day9 = lv_obj_create(ui_weatherporter);
    lv_obj_remove_style_all(ui_day9);
    lv_obj_set_width(ui_day9, 100);
    lv_obj_set_height(ui_day9, 161);
    lv_obj_set_x(ui_day9, 352);
    lv_obj_set_y(ui_day9, 136);
    lv_obj_set_align(ui_day9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_day9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_humanday9 = lv_label_create(ui_day9);
    lv_obj_set_width(ui_humanday9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humanday9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humanday9, -3);
    lv_obj_set_y(ui_humanday9, -50);
    lv_obj_set_align(ui_humanday9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humanday9, "Thu");
    lv_obj_remove_flag(ui_humanday9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_humanday9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humanday9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humanday9, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day9icon = lv_label_create(ui_day9);
    lv_obj_set_width(ui_day9icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day9icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day9icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day9icon, "B");
    lv_obj_remove_flag(ui_day9icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day9icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day9icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day9icon, &ui_font_weather96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day9deg = lv_label_create(ui_day9);
    lv_obj_set_width(ui_day9deg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day9deg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day9deg, 0);
    lv_obj_set_y(ui_day9deg, 50);
    lv_obj_set_align(ui_day9deg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day9deg, "0°");
    lv_obj_remove_flag(ui_day9deg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_day9deg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day9deg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day9deg, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextdaysep8 = lv_obj_create(ui_day9);
    lv_obj_set_width(ui_nextdaysep8, 2);
    lv_obj_set_height(ui_nextdaysep8, 170);
    lv_obj_set_x(ui_nextdaysep8, 47);
    lv_obj_set_y(ui_nextdaysep8, 0);
    lv_obj_set_align(ui_nextdaysep8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nextdaysep8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_nextdaysep8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator = lv_obj_create(ui_weatherporter);
    lv_obj_set_width(ui_separator, 805);
    lv_obj_set_height(ui_separator, 2);
    lv_obj_set_x(ui_separator, -2);
    lv_obj_set_y(ui_separator, 55);
    lv_obj_set_align(ui_separator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_separator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timekeep = lv_obj_create(ui_viewport);
    lv_obj_remove_style_all(ui_timekeep);
    lv_obj_set_width(ui_timekeep, 803);
    lv_obj_set_height(ui_timekeep, 400);
    lv_obj_set_x(ui_timekeep, 88);
    lv_obj_set_y(ui_timekeep, 17);
    lv_obj_set_align(ui_timekeep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timekeep, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_timekeep, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_snap_x(ui_timekeep, LV_SCROLL_SNAP_CENTER);

    ui_quote = lv_label_create(ui_timekeep);
    lv_obj_set_width(ui_quote, 732);
    lv_obj_set_height(ui_quote, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_quote, 1);
    lv_obj_set_y(ui_quote, 125);
    lv_obj_set_align(ui_quote, LV_ALIGN_CENTER);
    lv_label_set_text(ui_quote,
                      "\"To do is to be\" --Jean-Paul Sartre.\n\"To be is to do\" --Socrates.\n\"Scooby dooby doo\" --Scooby doo");
    lv_obj_add_flag(ui_quote, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_quote, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_quote, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_quote, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_quote, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_quote, &ui_font_quote30oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_timekeep);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -74);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "--:--");
    lv_obj_remove_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_clockface286oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_config = lv_obj_create(ui_viewport);
    lv_obj_remove_style_all(ui_config);
    lv_obj_set_width(ui_config, 800);
    lv_obj_set_height(ui_config, 415);
    lv_obj_set_x(ui_config, 0);
    lv_obj_set_y(ui_config, 29);
    lv_obj_set_align(ui_config, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_config, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_config, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_config, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi = lv_button_create(ui_config);
    lv_obj_set_width(ui_wifi, 700);
    lv_obj_set_height(ui_wifi, 50);
    lv_obj_set_x(ui_wifi, 0);
    lv_obj_set_y(ui_wifi, -126);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifi, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_wifi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconwifi = lv_label_create(ui_wifi);
    lv_obj_set_width(ui_iconwifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconwifi, -321);
    lv_obj_set_y(ui_iconwifi, 0);
    lv_obj_set_align(ui_iconwifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconwifi, "D");
    lv_obj_set_style_text_color(ui_iconwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconwifi, &ui_font_settings32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelwifi = lv_label_create(ui_wifi);
    lv_obj_set_width(ui_labelwifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelwifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelwifi, -204);
    lv_obj_set_y(ui_labelwifi, 1);
    lv_obj_set_align(ui_labelwifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelwifi, "CONNECTION");
    lv_obj_set_style_text_color(ui_labelwifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelwifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelwifi, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timezone = lv_button_create(ui_config);
    lv_obj_set_width(ui_timezone, 700);
    lv_obj_set_height(ui_timezone, 50);
    lv_obj_set_x(ui_timezone, 0);
    lv_obj_set_y(ui_timezone, -53);
    lv_obj_set_align(ui_timezone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timezone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_timezone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_timezone, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timezone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timezone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timezone, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_timezone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_timezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_timezone, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_timezone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconglobe = lv_label_create(ui_timezone);
    lv_obj_set_width(ui_iconglobe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconglobe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconglobe, -321);
    lv_obj_set_y(ui_iconglobe, 0);
    lv_obj_set_align(ui_iconglobe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconglobe, "A");
    lv_obj_set_style_text_color(ui_iconglobe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconglobe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconglobe, &ui_font_settings32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labeltimezone = lv_label_create(ui_timezone);
    lv_obj_set_width(ui_labeltimezone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltimezone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltimezone, -220);
    lv_obj_set_y(ui_labeltimezone, 1);
    lv_obj_set_align(ui_labeltimezone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltimezone, "LOCATION");
    lv_obj_set_style_text_color(ui_labeltimezone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labeltimezone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltimezone, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_units = lv_button_create(ui_config);
    lv_obj_set_width(ui_units, 700);
    lv_obj_set_height(ui_units, 50);
    lv_obj_set_x(ui_units, 0);
    lv_obj_set_y(ui_units, 21);
    lv_obj_set_align(ui_units, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_units, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_units, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_units, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_units, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_units, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_units, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_units, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_units, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_units, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_units, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_units, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_units, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconunits = lv_label_create(ui_units);
    lv_obj_set_width(ui_iconunits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconunits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconunits, -321);
    lv_obj_set_y(ui_iconunits, 0);
    lv_obj_set_align(ui_iconunits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iconunits, "C");
    lv_obj_set_style_text_color(ui_iconunits, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iconunits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iconunits, &ui_font_settings32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelunits = lv_label_create(ui_units);
    lv_obj_set_width(ui_labelunits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelunits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelunits, -244);
    lv_obj_set_y(ui_labelunits, 1);
    lv_obj_set_align(ui_labelunits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelunits, "UNITS");
    lv_obj_set_style_text_color(ui_labelunits, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelunits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelunits, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifi, ui_event_wifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timezone, ui_event_timezone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_units, ui_event_units, LV_EVENT_ALL, NULL);
    uic_todayweek = ui_todayweek;

}

void ui_main_screen_destroy(void)
{
    if(ui_main) lv_obj_del(ui_main);

    // NULL screen variables
    ui_main = NULL;
    ui_dateandwifi = NULL;
    ui_wifiStrength = NULL;
    ui_date = NULL;
    ui_border = NULL;
    ui_viewport = NULL;
    ui_weatherporter = NULL;
    ui_day2 = NULL;
    ui_humanday2 = NULL;
    ui_nextdaysep1 = NULL;
    ui_day2icon = NULL;
    ui_day2deg = NULL;
    ui_next4days = NULL;
    ui_todayweather = NULL;
    ui_day1 = NULL;
    ui_todayicon = NULL;
    uic_todayweek = NULL;
    ui_todayweek = NULL;
    ui_day3 = NULL;
    ui_humanday3 = NULL;
    ui_nextdaysep2 = NULL;
    ui_day3icon = NULL;
    ui_day3deg = NULL;
    ui_day4 = NULL;
    ui_humanday4 = NULL;
    ui_nextdaysep3 = NULL;
    ui_day4icon = NULL;
    ui_day4deg = NULL;
    ui_day5 = NULL;
    ui_humanday5 = NULL;
    ui_nextdaysep4 = NULL;
    ui_day5icon = NULL;
    ui_day5deg = NULL;
    ui_day6 = NULL;
    ui_humanday6 = NULL;
    ui_nextdaysep5 = NULL;
    ui_day6icon = NULL;
    ui_day6deg = NULL;
    ui_day7 = NULL;
    ui_humanday7 = NULL;
    ui_nextdaysep6 = NULL;
    ui_day7icon = NULL;
    ui_day7deg = NULL;
    ui_day8 = NULL;
    ui_humanday8 = NULL;
    ui_nextdaysep7 = NULL;
    ui_day8icon = NULL;
    ui_day8deg = NULL;
    ui_day9 = NULL;
    ui_humanday9 = NULL;
    ui_day9icon = NULL;
    ui_day9deg = NULL;
    ui_nextdaysep8 = NULL;
    ui_separator = NULL;
    ui_timekeep = NULL;
    ui_quote = NULL;
    ui_time = NULL;
    ui_config = NULL;
    ui_wifi = NULL;
    ui_iconwifi = NULL;
    ui_labelwifi = NULL;
    ui_timezone = NULL;
    ui_iconglobe = NULL;
    ui_labeltimezone = NULL;
    ui_units = NULL;
    ui_iconunits = NULL;
    ui_labelunits = NULL;

}
