// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_wifiStrength = NULL;
lv_obj_t * ui_quote = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -36);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "10:07");
    lv_obj_remove_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_clockface286bpp4numbersv2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -310);
    lv_obj_set_y(ui_date, -197);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "06/07");
    lv_obj_remove_flag(ui_date, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_robotomono26mediumbpp4v2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStrength = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_wifiStrength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStrength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStrength, 310);
    lv_obj_set_y(ui_wifiStrength, -196);
    lv_obj_set_align(ui_wifiStrength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiStrength, "-45dBm");
    lv_obj_remove_flag(ui_wifiStrength, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_wifiStrength, lv_color_hex(0x0CB311), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiStrength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiStrength, &ui_font_robotomono26mediumbpp4v2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_quote = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_quote, 718);
    lv_obj_set_height(ui_quote, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_quote, 1);
    lv_obj_set_y(ui_quote, 141);
    lv_obj_set_align(ui_quote, LV_ALIGN_CENTER);
    lv_label_set_text(ui_quote,
                      "\"To do is to be\" --Jean-Paul Sartre.\n\"To be is to do\" --Socrates.\n\"Scooby dooby doo\" --Scooby doo");
    lv_obj_remove_flag(ui_quote, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_quote, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_quote, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_quote, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_quote, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_time = NULL;
    ui_date = NULL;
    ui_wifiStrength = NULL;
    ui_quote = NULL;

}
