// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_unitsscreen = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_corf = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_cancel1 = NULL;
lv_obj_t * ui_coonect4 = NULL;
lv_obj_t * ui_notacancelbutton3 = NULL;
lv_obj_t * ui_coonect5 = NULL;
// event funtions
void ui_event_cancel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_main_screen_init);
    }
}

void ui_event_notacancelbutton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_main_screen_init);
        saveunits(e);
    }
}

// build funtions

void ui_unitsscreen_screen_init(void)
{
    ui_unitsscreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_unitsscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_unitsscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_unitsscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_unitsscreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -207);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SET UNITS (and nothing more...)");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_corf = lv_dropdown_create(ui_unitsscreen);
    lv_dropdown_set_options(ui_corf, "Celcius\nFarenheit");
    lv_obj_set_width(ui_corf, 169);
    lv_obj_set_height(ui_corf, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_corf, -168);
    lv_obj_set_y(ui_corf, -56);
    lv_obj_set_align(ui_corf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_corf, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_corf, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_corf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_corf, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_corf, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_corf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_corf), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_corf), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_corf), lv_color_hex(0x131313),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_corf), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_unitsscreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -320);
    lv_obj_set_y(ui_Label7, -56);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "UNITS:");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancel1 = lv_button_create(ui_unitsscreen);
    lv_obj_set_width(ui_cancel1, 248);
    lv_obj_set_height(ui_cancel1, 41);
    lv_obj_set_x(ui_cancel1, -254);
    lv_obj_set_y(ui_cancel1, 25);
    lv_obj_set_align(ui_cancel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cancel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cancel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cancel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cancel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cancel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cancel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cancel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_cancel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coonect4 = lv_label_create(ui_cancel1);
    lv_obj_set_width(ui_coonect4, 233);
    lv_obj_set_height(ui_coonect4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coonect4, 0);
    lv_obj_set_y(ui_coonect4, 1);
    lv_obj_set_align(ui_coonect4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coonect4, "CANCEL");
    lv_obj_set_style_text_color(ui_coonect4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coonect4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coonect4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coonect4, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notacancelbutton3 = lv_button_create(ui_unitsscreen);
    lv_obj_set_width(ui_notacancelbutton3, 248);
    lv_obj_set_height(ui_notacancelbutton3, 41);
    lv_obj_set_x(ui_notacancelbutton3, 254);
    lv_obj_set_y(ui_notacancelbutton3, 25);
    lv_obj_set_align(ui_notacancelbutton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_notacancelbutton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_notacancelbutton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_notacancelbutton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_notacancelbutton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_notacancelbutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_notacancelbutton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_notacancelbutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_notacancelbutton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_notacancelbutton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_notacancelbutton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_notacancelbutton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_notacancelbutton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coonect5 = lv_label_create(ui_notacancelbutton3);
    lv_obj_set_width(ui_coonect5, 233);
    lv_obj_set_height(ui_coonect5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coonect5, 0);
    lv_obj_set_y(ui_coonect5, 1);
    lv_obj_set_align(ui_coonect5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coonect5, "SAVE");
    lv_obj_set_style_text_color(ui_coonect5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coonect5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coonect5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coonect5, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cancel1, ui_event_cancel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_notacancelbutton3, ui_event_notacancelbutton3, LV_EVENT_ALL, NULL);

}

void ui_unitsscreen_screen_destroy(void)
{
    if(ui_unitsscreen) lv_obj_del(ui_unitsscreen);

    // NULL screen variables
    ui_unitsscreen = NULL;
    ui_Label6 = NULL;
    ui_corf = NULL;
    ui_Label7 = NULL;
    ui_cancel1 = NULL;
    ui_coonect4 = NULL;
    ui_notacancelbutton3 = NULL;
    ui_coonect5 = NULL;

}
