// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_UNITSSCREEN_H
#define UI_UNITSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_unitsscreen
extern void ui_unitsscreen_screen_init(void);
extern void ui_unitsscreen_screen_destroy(void);
extern lv_obj_t * ui_unitsscreen;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_corf;
extern lv_obj_t * ui_Label7;
extern void ui_event_cancel1(lv_event_t * e);
extern lv_obj_t * ui_cancel1;
extern lv_obj_t * ui_coonect4;
extern void ui_event_notacancelbutton3(lv_event_t * e);
extern lv_obj_t * ui_notacancelbutton3;
extern lv_obj_t * ui_coonect5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

