// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifiscreen
extern void ui_wifiscreen_screen_init(void);
extern void ui_wifiscreen_screen_destroy(void);
extern lv_obj_t * ui_wifiscreen;
extern void ui_event_ssidta(lv_event_t * e);
extern lv_obj_t * ui_ssidta;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ssid;
extern void ui_event_keyta(lv_event_t * e);
extern lv_obj_t * ui_keyta;
extern lv_obj_t * ui_key;
extern void ui_event_connect(lv_event_t * e);
extern lv_obj_t * ui_connect;
extern lv_obj_t * ui_coonect;
extern void ui_event_cancelbutton(lv_event_t * e);
extern lv_obj_t * ui_cancelbutton;
extern lv_obj_t * ui_cancel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

