// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_wifiscreen = NULL;
lv_obj_t * ui_ssidta = NULL;
lv_obj_t * ui_Keyboard = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ssid = NULL;
lv_obj_t * ui_keyta = NULL;
lv_obj_t * ui_key = NULL;
lv_obj_t * ui_connect = NULL;
lv_obj_t * ui_coonect = NULL;
lv_obj_t * ui_cancelbutton = NULL;
lv_obj_t * ui_cancel = NULL;
// event funtions
void ui_event_ssidta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_ssidta);
    }
}

void ui_event_keyta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_keyta);
    }
}

void ui_event_connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_main_screen_init);
        connect2wifi(e);
    }
}

void ui_event_cancelbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 150, &ui_main_screen_init);
    }
}

// build funtions

void ui_wifiscreen_screen_init(void)
{
    ui_wifiscreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_wifiscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssidta = lv_textarea_create(ui_wifiscreen);
    lv_obj_set_width(ui_ssidta, 742);
    lv_obj_set_height(ui_ssidta, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_ssidta, 0);
    lv_obj_set_y(ui_ssidta, -146);
    lv_obj_set_align(ui_ssidta, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_ssidta, true);
    lv_obj_set_style_text_color(ui_ssidta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssidta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ssidta, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ssidta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ssidta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ssidta, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ssidta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ssidta, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ssidta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ssidta, 2, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_wifiscreen);
    lv_obj_set_width(ui_Keyboard, 800);
    lv_obj_set_height(ui_Keyboard, 201);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 139);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xB7B7B7), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x848484), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Keyboard, 255, LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_wifiscreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -211);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "CONNECT TO WIFI");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssid = lv_label_create(ui_wifiscreen);
    lv_obj_set_width(ui_ssid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssid, -337);
    lv_obj_set_y(ui_ssid, -191);
    lv_obj_set_align(ui_ssid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssid, "SSID");
    lv_obj_set_style_text_color(ui_ssid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssid, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keyta = lv_textarea_create(ui_wifiscreen);
    lv_obj_set_width(ui_keyta, 742);
    lv_obj_set_height(ui_keyta, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_keyta, 0);
    lv_obj_set_y(ui_keyta, -47);
    lv_obj_set_align(ui_keyta, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_keyta, true);
    lv_textarea_set_password_mode(ui_keyta, true);
    lv_obj_set_style_text_color(ui_keyta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_keyta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_keyta, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_keyta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keyta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_keyta, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keyta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_keyta, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_keyta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_keyta, 2, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_key = lv_label_create(ui_wifiscreen);
    lv_obj_set_width(ui_key, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_key, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_key, -343);
    lv_obj_set_y(ui_key, -93);
    lv_obj_set_align(ui_key, LV_ALIGN_CENTER);
    lv_label_set_text(ui_key, "KEY");
    lv_obj_set_style_text_color(ui_key, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_key, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_key, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connect = lv_button_create(ui_wifiscreen);
    lv_obj_set_width(ui_connect, 248);
    lv_obj_set_height(ui_connect, 41);
    lv_obj_set_x(ui_connect, 250);
    lv_obj_set_y(ui_connect, 16);
    lv_obj_set_align(ui_connect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connect, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_connect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_connect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_connect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coonect = lv_label_create(ui_connect);
    lv_obj_set_width(ui_coonect, 233);
    lv_obj_set_height(ui_coonect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coonect, 0);
    lv_obj_set_y(ui_coonect, 1);
    lv_obj_set_align(ui_coonect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coonect, "CONNECT");
    lv_obj_set_style_text_color(ui_coonect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coonect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_coonect, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coonect, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbutton = lv_button_create(ui_wifiscreen);
    lv_obj_set_width(ui_cancelbutton, 248);
    lv_obj_set_height(ui_cancelbutton, 41);
    lv_obj_set_x(ui_cancelbutton, -250);
    lv_obj_set_y(ui_cancelbutton, 16);
    lv_obj_set_align(ui_cancelbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancelbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cancelbutton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cancelbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cancelbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cancelbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancelbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cancelbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cancelbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cancelbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_cancelbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancel = lv_label_create(ui_cancelbutton);
    lv_obj_set_width(ui_cancel, 233);
    lv_obj_set_height(ui_cancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cancel, 0);
    lv_obj_set_y(ui_cancel, 1);
    lv_obj_set_align(ui_cancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cancel, "CANCEL");
    lv_obj_set_style_text_color(ui_cancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cancel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cancel, &ui_font_status26oPTimized, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ssidta, ui_event_ssidta, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_ssidta);
    lv_obj_add_event_cb(ui_keyta, ui_event_keyta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connect, ui_event_connect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbutton, ui_event_cancelbutton, LV_EVENT_ALL, NULL);

}

void ui_wifiscreen_screen_destroy(void)
{
    if(ui_wifiscreen) lv_obj_del(ui_wifiscreen);

    // NULL screen variables
    ui_wifiscreen = NULL;
    ui_ssidta = NULL;
    ui_Keyboard = NULL;
    ui_Label3 = NULL;
    ui_ssid = NULL;
    ui_keyta = NULL;
    ui_key = NULL;
    ui_connect = NULL;
    ui_coonect = NULL;
    ui_cancelbutton = NULL;
    ui_cancel = NULL;

}
